import {
  booleanParam,
  countryCodeListParam,
  countryCodeParam,
  enumListParam,
  enumParam,
  fieldNameParam,
  int64Id,
  limitParam,
  offsetParam,
  productPageId,
  stringListParam,
  textParam,
  V5_LIST_PAGINATION,
  v5FieldsParam,
  v5ListQueryParams,
} from './params.js';
import type { EndpointDefinition } from './types.js';

/**
 * Every GET endpoint of the Apple Search Ads Campaign Management API v5
 * (https://developer.apple.com/documentation/apple_ads), base URL https://api.searchads.apple.com/api/v5.
 *
 * Source: Apple's official documentation (API 5, changelog through 5.6 / June 2026). Non-GET endpoints
 * (including read-style POST /find and POST /reports endpoints) are intentionally not implemented; see
 * docs/api-coverage.json -> excluded.
 */

const api = 'campaign-management-v5' as const;
const campaignId = int64Id('The unique identifier for the campaign');
const adgroupId = int64Id('The unique identifier for the ad group');
const adamId = int64Id('The App Store app identifier (adamId)');

export const CAMPAIGN_MANAGEMENT_V5_ENDPOINTS: readonly EndpointDefinition[] = [
  // ---------------------------------------------------------------- User access
  {
    id: 'v5.getUserAcl',
    toolName: 'v5_get_user_acl',
    api,
    category: 'User Access',
    title: 'Get User ACL',
    description:
      'Fetches the roles and organizations (orgId, orgName, currency, timeZone, paymentModel, roleNames) the API user can access. Use it to discover org_id values. Does not require an org context.',
    method: 'GET',
    path: '/acls',
    pathParams: {},
    queryParams: {},
    requiresContext: false,
    docSlug: 'get-user-acl',
    responseType: 'UserAclListResponse',
  },
  {
    id: 'v5.getMeDetails',
    toolName: 'v5_get_me_details',
    api,
    category: 'User Access',
    title: 'Get Me Details',
    description: "Fetches the API caller's userId and parentOrgId. Does not require an org context.",
    method: 'GET',
    path: '/me',
    pathParams: {},
    queryParams: {},
    requiresContext: false,
    docSlug: 'get-me-details',
    responseType: 'MeDetailResponse',
  },
  // ---------------------------------------------------------------- Apps
  {
    id: 'v5.searchApps',
    toolName: 'v5_search_apps',
    api,
    category: 'Apps',
    title: 'Search for iOS Apps',
    description:
      'Searches App Store apps by name prefix (minimum three characters) and returns adamId, appName, developerName and countryOrRegionCodes. Set returnOwnedApps=true to only return apps owned by the organization.',
    method: 'GET',
    path: '/search/apps',
    pathParams: {},
    queryParams: {
      query: textParam('App name prefix to search for (Apple requires at least three characters).', {
        required: true,
      }),
      returnOwnedApps: booleanParam('Only return apps that belong to your organization (default false).'),
      ...v5ListQueryParams(),
    },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'search-for-ios-apps',
    responseType: 'AppInfoListResponse',
  },
  {
    id: 'v5.getAppDetails',
    toolName: 'v5_get_app_details',
    api,
    category: 'App Details',
    title: 'Get App Details',
    description:
      'Fetches App Store metadata for an app: name, artist, primary language and genres, device classes, icon URL, pre-order flag and available storefronts.',
    method: 'GET',
    path: '/apps/{adamId}',
    pathParams: { adamId },
    queryParams: {},
    requiresContext: true,
    docSlug: 'get-app-details',
    responseType: 'MediaDetailResponse',
  },
  {
    id: 'v5.getLocalizedAppDetails',
    toolName: 'v5_get_localized_app_details',
    api,
    category: 'App Details',
    title: 'Get Localized App Details',
    description:
      'Fetches the localized default product page details for an app (per-language name, subtitle, short description and optionally screenshot/app preview assets).',
    method: 'GET',
    path: '/apps/{adamId}/locale-details',
    pathParams: { adamId },
    queryParams: {
      expand: booleanParam(
        'Set true to include detailed app asset (screenshot / app preview) details per device.',
      ),
    },
    requiresContext: true,
    docSlug: 'get-localized-app-details',
    responseType: 'MediaLocaleDetailResponse',
  },
  // ---------------------------------------------------------------- Campaigns
  {
    id: 'v5.getCampaign',
    toolName: 'v5_get_campaign',
    api,
    category: 'Campaigns',
    title: 'Get a Campaign',
    description:
      'Fetches a single campaign by id (budget, bidding strategy, countries/regions, supply sources, status, serving status and reasons). Returns deleted campaigns as well.',
    method: 'GET',
    path: '/campaigns/{campaignId}',
    pathParams: { campaignId },
    queryParams: { fields: v5FieldsParam() },
    requiresContext: true,
    docSlug: 'get-a-campaign',
    responseType: 'CampaignResponse',
  },
  {
    id: 'v5.getAllCampaigns',
    toolName: 'v5_get_all_campaigns',
    api,
    category: 'Campaigns',
    title: 'Get all Campaigns',
    description: 'Lists the campaigns in the organization. Supports limit/offset paging and fetch_all.',
    method: 'GET',
    path: '/campaigns',
    pathParams: {},
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-campaigns',
    responseType: 'CampaignListResponse',
  },
  // ---------------------------------------------------------------- Budget orders
  {
    id: 'v5.getBudgetOrder',
    toolName: 'v5_get_budget_order',
    api,
    category: 'Budget Orders',
    title: 'Get a Budget Order',
    description:
      'Fetches a budget order (LOC / monthly-invoicing organizations) by id, including completed and canceled orders.',
    method: 'GET',
    path: '/budgetorders/{boId}',
    pathParams: { boId: int64Id('The unique identifier for the budget order') },
    queryParams: { fields: v5FieldsParam() },
    requiresContext: true,
    docSlug: 'get-a-budget-order',
    responseType: 'BudgetOrderInfoResponse',
  },
  {
    id: 'v5.getAllBudgetOrders',
    toolName: 'v5_get_all_budget_orders',
    api,
    category: 'Budget Orders',
    title: 'Get all Budget Orders',
    description: 'Lists all budget orders in the organization, including completed and canceled orders.',
    method: 'GET',
    path: '/budgetorders',
    pathParams: {},
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-budget-orders',
    responseType: 'BudgetOrderInfoListResponse',
  },
  // ---------------------------------------------------------------- Ad groups
  {
    id: 'v5.getAdGroup',
    toolName: 'v5_get_ad_group',
    api,
    category: 'Ad Groups',
    title: 'Get an Ad Group',
    description:
      'Fetches a single ad group in a campaign (bids, CPA goal, targeting dimensions, status and serving status).',
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups/{adgroupId}',
    pathParams: { campaignId, adgroupId },
    queryParams: { fields: v5FieldsParam() },
    requiresContext: true,
    docSlug: 'get-an-ad-group',
    responseType: 'AdGroupResponse',
  },
  {
    id: 'v5.getAllAdGroups',
    toolName: 'v5_get_all_ad_groups',
    api,
    category: 'Ad Groups',
    title: 'Get all Ad Groups',
    description: 'Lists the ad groups in a campaign. Supports limit/offset paging and fetch_all.',
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups',
    pathParams: { campaignId },
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-ad-groups',
    responseType: 'AdGroupListResponse',
  },
  // ---------------------------------------------------------------- Targeting keywords
  {
    id: 'v5.getTargetingKeyword',
    toolName: 'v5_get_targeting_keyword',
    api,
    category: 'Targeting Keywords',
    title: 'Get a Targeting Keyword in an Ad Group',
    description: 'Fetches a single targeting keyword (text, match type, bid, status) in an ad group.',
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups/{adgroupId}/targetingkeywords/{keywordId}',
    pathParams: {
      campaignId,
      adgroupId,
      keywordId: int64Id('The unique identifier for the targeting keyword'),
    },
    queryParams: { fields: v5FieldsParam() },
    requiresContext: true,
    docSlug: 'get-a-targeting-keyword-in-an-ad-group',
    responseType: 'KeywordResponse',
  },
  {
    id: 'v5.getAllTargetingKeywords',
    toolName: 'v5_get_all_targeting_keywords',
    api,
    category: 'Targeting Keywords',
    title: 'Get All Targeting Keywords in an Ad Group',
    description: 'Lists the targeting keywords in an ad group. Supports limit/offset paging and fetch_all.',
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups/{adgroupId}/targetingkeywords',
    pathParams: { campaignId, adgroupId },
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-targeting-keywords-in-an-ad-group',
    responseType: 'KeywordListResponse',
  },
  // ---------------------------------------------------------------- Campaign negative keywords
  {
    id: 'v5.getCampaignNegativeKeyword',
    toolName: 'v5_get_campaign_negative_keyword',
    api,
    category: 'Campaign Negative Keywords',
    title: 'Get a Campaign Negative Keyword',
    description: 'Fetches a single campaign-level negative keyword.',
    method: 'GET',
    path: '/campaigns/{campaignId}/negativekeywords/{keywordId}',
    pathParams: { campaignId, keywordId: int64Id('The unique identifier for the negative keyword') },
    queryParams: { fields: v5FieldsParam() },
    requiresContext: true,
    docSlug: 'get-a-campaign-negative-keyword',
    responseType: 'NegativeKeywordResponse',
  },
  {
    id: 'v5.getAllCampaignNegativeKeywords',
    toolName: 'v5_get_all_campaign_negative_keywords',
    api,
    category: 'Campaign Negative Keywords',
    title: 'Get All Campaign Negative Keywords',
    description: 'Lists the campaign-level negative keywords. Supports limit/offset paging and fetch_all.',
    method: 'GET',
    path: '/campaigns/{campaignId}/negativekeywords',
    pathParams: { campaignId },
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-campaign-negative-keywords',
    responseType: 'NegativeKeywordListResponse',
  },
  // ---------------------------------------------------------------- Ad group negative keywords
  {
    id: 'v5.getAdGroupNegativeKeyword',
    toolName: 'v5_get_ad_group_negative_keyword',
    api,
    category: 'Ad Group Negative Keywords',
    title: 'Get an Ad Group Negative Keyword',
    description: 'Fetches a single ad-group-level negative keyword.',
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups/{adgroupId}/negativekeywords/{keywordId}',
    pathParams: {
      campaignId,
      adgroupId,
      keywordId: int64Id('The unique identifier for the negative keyword'),
    },
    queryParams: { fields: v5FieldsParam() },
    requiresContext: true,
    docSlug: 'get-an-ad-group-negative-keyword',
    responseType: 'NegativeKeywordResponse',
  },
  {
    id: 'v5.getAllAdGroupNegativeKeywords',
    toolName: 'v5_get_all_ad_group_negative_keywords',
    api,
    category: 'Ad Group Negative Keywords',
    title: 'Get All Ad Group Negative Keywords',
    description: 'Lists the negative keywords of an ad group. Supports limit/offset paging and fetch_all.',
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups/{adgroupId}/negativekeywords',
    pathParams: { campaignId, adgroupId },
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-ad-group-negative-keywords',
    responseType: 'NegativeKeywordListResponse',
  },
  // ---------------------------------------------------------------- Geolocations
  {
    id: 'v5.searchGeolocations',
    toolName: 'v5_search_geolocations',
    api,
    category: 'Search Geolocations',
    title: 'Search for Geolocations',
    description:
      'Searches geo-targeting locations (Country, AdminArea, Locality) by name prefix. Returns ids such as "US|CA|Cupertino" for ad group targeting.',
    method: 'GET',
    path: '/search/geo',
    pathParams: {},
    queryParams: {
      query: textParam(
        'Name prefix to search for (Apple default "*:*"; prefix matching, minimum three characters).',
      ),
      entity: enumParam(
        ['Country', 'AdminArea', 'Locality'] as const,
        'The geolocation entity type to search.',
      ),
      countrycode: countryCodeParam('Country or region to search within (Apple default "US")'),
      ...v5ListQueryParams(),
    },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'search-for-geolocations',
    responseType: 'SearchEntityListResponse',
  },
  // ---------------------------------------------------------------- Ads
  {
    id: 'v5.getAd',
    toolName: 'v5_get_ad',
    api,
    category: 'Ads',
    title: 'Get an Ad',
    description: 'Fetches an ad assigned to an ad group (creative, creative type, status and serving state).',
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups/{adgroupId}/ads/{adId}',
    pathParams: { campaignId, adgroupId, adId: int64Id('The unique identifier of the ad') },
    queryParams: { fields: v5FieldsParam() },
    requiresContext: true,
    docSlug: 'get-an-ad',
    responseType: 'AdResponse',
  },
  {
    id: 'v5.getAllAds',
    toolName: 'v5_get_all_ads',
    api,
    category: 'Ads',
    title: 'Get All Ads',
    description:
      "Lists the ads in an ad group. limit/offset follow Apple's general GET pagination rules (they are not listed on this endpoint's page).",
    method: 'GET',
    path: '/campaigns/{campaignId}/adgroups/{adgroupId}/ads',
    pathParams: { campaignId, adgroupId },
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-ads',
    responseType: 'AdListResponse',
    notes: [
      "limit/offset come from Apple's general Pagination rules; the endpoint page lists no query parameters.",
    ],
  },
  // ---------------------------------------------------------------- Ad rejection reasons
  {
    id: 'v5.getAdCreativeRejectionReason',
    toolName: 'v5_get_ad_creative_rejection_reason',
    api,
    category: 'Ad Rejection Reasons',
    title: 'Get Ad Creative Rejection Reasons',
    description: 'Fetches a product page (ad creative) rejection reason by id.',
    method: 'GET',
    path: '/product-page-reasons/{productPageReasonId}',
    pathParams: { productPageReasonId: int64Id('The unique identifier of the product page reason') },
    queryParams: {},
    requiresContext: true,
    docSlug: 'gets-a-product-page-reason',
    responseType: 'ProductPageReasonResponse',
  },
  // ---------------------------------------------------------------- Creatives
  {
    id: 'v5.getCreative',
    toolName: 'v5_get_creative',
    api,
    category: 'Creatives',
    title: 'Get a Creative',
    description: 'Fetches a creative (custom or default product page creative) by id.',
    method: 'GET',
    path: '/creatives/{creativeId}',
    pathParams: { creativeId: int64Id('The unique identifier for the creative') },
    queryParams: {
      includeDeletedCreativeSetAssets: booleanParam(
        'Include deleted assets in the response (default false).',
      ),
      fields: v5FieldsParam(),
    },
    requiresContext: true,
    docSlug: 'get-a-creative',
    responseType: 'CreativeResponse',
  },
  {
    id: 'v5.getAllCreatives',
    toolName: 'v5_get_all_creatives',
    api,
    category: 'Creatives',
    title: 'Get All Creatives',
    description: 'Lists all creatives in the organization. Supports limit/offset paging and fetch_all.',
    method: 'GET',
    path: '/creatives',
    pathParams: {},
    queryParams: { ...v5ListQueryParams(), fields: v5FieldsParam() },
    requiresContext: true,
    pagination: V5_LIST_PAGINATION,
    docSlug: 'get-all-creatives',
    responseType: 'CreativeListResponse',
  },
  // ---------------------------------------------------------------- Custom product pages
  {
    id: 'v5.getProductPages',
    toolName: 'v5_get_product_pages',
    api,
    category: 'Custom Product Pages',
    title: 'Get Product Pages',
    description: 'Lists the custom product pages of an app, optionally filtered by name or state.',
    method: 'GET',
    path: '/apps/{adamId}/product-pages',
    pathParams: { adamId },
    queryParams: {
      name: textParam('Filter by custom product page name.'),
      states: enumParam(['HIDDEN', 'VISIBLE'] as const, 'Filter by product page state.'),
    },
    requiresContext: true,
    docSlug: 'get-product-pages',
    responseType: 'ProductPageDetailListResponse',
  },
  {
    id: 'v5.getProductPage',
    toolName: 'v5_get_product_page',
    api,
    category: 'Custom Product Pages',
    title: 'Get Product Pages by Identifier',
    description: 'Fetches a single custom product page of an app (name, state, deep link).',
    method: 'GET',
    path: '/apps/{adamId}/product-pages/{productPageId}',
    pathParams: { adamId, productPageId: productPageId('The custom product page identifier') },
    queryParams: {},
    requiresContext: true,
    docSlug: 'get-product-pages-by-identifier',
    responseType: 'ProductPageDetailResponse',
  },
  {
    id: 'v5.getProductPageLocales',
    toolName: 'v5_get_product_page_locales',
    api,
    category: 'Custom Product Pages',
    title: 'Get Product Page Locales',
    description:
      'Fetches the localized metadata of a custom product page (app name, subtitle, promotional text, device classes; with expand=true also screenshots and app previews).',
    method: 'GET',
    path: '/apps/{adamId}/product-pages/{productPageId}/locale-details',
    pathParams: { adamId, productPageId: productPageId('The custom product page identifier') },
    queryParams: {
      deviceClasses: enumListParam(['IPAD', 'IPHONE'] as const, 'Filter by device class.'),
      expand: booleanParam('Set true for expanded asset values (default false).'),
      languageCodes: stringListParam(
        'Filter by language codes, e.g. ["en-US", "fr-CA"].',
        /^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})*$/,
        'must be a language code such as en-US',
        50,
      ),
      languages: textParam('Filter by language (as documented by Apple, e.g. "US").', { maxLength: 64 }),
    },
    requiresContext: true,
    docSlug: 'get-product-page-locales',
    responseType: 'ProductPageLocaleDetailListResponse',
  },
  {
    id: 'v5.getSupportedCountriesOrRegions',
    toolName: 'v5_get_supported_countries_or_regions',
    api,
    category: 'Custom Product Pages',
    title: 'Get Supported Countries or Regions',
    description: 'Fetches supported countries or regions with their supported and default languages.',
    method: 'GET',
    path: '/countries-or-regions',
    pathParams: {},
    queryParams: {
      countriesOrRegions: countryCodeListParam('Only return these countries or regions', 'csv'),
    },
    requiresContext: true,
    docSlug: 'get-supported-countries-or-regions',
    responseType: 'CountriesOrRegionsListResponse',
  },
  {
    id: 'v5.getAppPreviewDeviceSizes',
    toolName: 'v5_get_app_preview_device_sizes',
    api,
    category: 'Custom Product Pages',
    title: 'Get App Preview Device Sizes',
    description:
      'Fetches the mapping of app preview device keys to display sizes (e.g. "iphone_6_5" -> "iPhone 6.5").',
    method: 'GET',
    path: '/creativeappmappings/devices',
    pathParams: {},
    queryParams: {},
    requiresContext: true,
    docSlug: 'get-app-preview-device-sizes',
    responseType: 'AppPreviewDevicesMappingResponse',
  },
  // ---------------------------------------------------------------- Impression share reports
  {
    id: 'v5.getImpressionShareReport',
    toolName: 'v5_get_impression_share_report',
    api,
    category: 'Impression Share Reports',
    title: 'Get a Single Impression Share Report',
    description:
      'Fetches an existing impression share (custom) report by id, including its state and, once COMPLETED, its downloadUri (valid for 90 seconds). Creating reports requires POST and is not supported.',
    method: 'GET',
    path: '/custom-reports/{reportId}',
    pathParams: { reportId: int64Id('The impression share report identifier') },
    queryParams: {},
    requiresContext: true,
    docSlug: 'get-a-single-impression-share-report',
    responseType: 'CustomReportResponseBody',
  },
  {
    id: 'v5.getAllImpressionShareReports',
    toolName: 'v5_get_all_impression_share_reports',
    api,
    category: 'Impression Share Reports',
    title: 'Get All Impression Share Reports',
    description:
      'Lists existing impression share (custom) reports. Apple allows at most 50 per page; sortable by a field (default creationTime).',
    method: 'GET',
    path: '/custom-reports',
    pathParams: {},
    queryParams: {
      field: fieldNameParam('Field to sort by (Apple default "creationTime").'),
      limit: limitParam({ max: 50, defaultValue: 20 }),
      offset: offsetParam(),
      sortOrder: enumParam(['ASCENDING', 'DESCENDING'] as const, 'Sort order (Apple default DESCENDING).'),
    },
    requiresContext: true,
    pagination: { ...V5_LIST_PAGINATION, maxPageSize: 50, fetchAllPageSize: 50 },
    docSlug: 'get-all-impression-share-reports',
    responseType: 'CustomReportResponseBody',
  },
];
